<a href="https://colab.research.google.com/github/LifeBreeze/2-2-math/blob/main/%5B03%5DSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 간단한 집합 연산

In [ ]:
s1 = set([1,2,3 ]) # 집합 {1,2,3} 선언
print(s1) # {1,2,3}
s2 = set([2,3,4])
print(s2)

print(s1&s2) # 교집합 {2,3}
print(s1 | s2) # 합집합 {1,2,3,4}
print(s1 - s2) # 차집합 {1}

{1, 2, 3}
{2, 3, 4}
{2, 3}
{1, 2, 3, 4}
{1}


### 두 은행의 고객 집합 합병

In [ ]:
# 두 은행의 고객 집합 선언
bankA_customers = set(["김철수", "이영희", "박민수", "최지우"])
bankB_customers = set(["이영희", "최지우", "정우성", "한지민"])

print("은행 A 고객 : ", bankA_customers)
print("은행 B 고객 : ", bankB_customers)

# 두 은행의 전체 고객 집합 (합집합)
total_customers = bankA_customers | bankB_customers
print("합병 후 전체 고객 : ", total_customers)

# 두 은행 모두에 있는 공통 고객 (교집합)
common_customers = bankA_customers & bankB_customers
print("공통 고객 : ",common_customers)

# A 은행에만 있는 고객 (차집합)
only_A_customers = bankA_customers - bankB_customers
print("A 은행에만 있는 고객 : ", only_A_customers)

# B 은행에만 있는 고객 (차집합)
only_B_customers = bankB_customers - bankA_customers
print("B 은행에만 있는 고객 : ", only_B_customers)


은행 A 고객 :  {'김철수', '박민수', '최지우', '이영희'}
은행 B 고객 :  {'한지민', '이영희', '정우성', '최지우'}
합병 후 전체 고객 :  {'이영희', '박민수', '최지우', '한지민', '정우성', '김철수'}
공통 고객 :  {'이영희', '최지우'}
A 은행에만 있는 고객 :  {'김철수', '박민수'}
B 은행에만 있는 고객 :  {'한지민', '정우성'}


### 임의의 입력 색상을 받아, 12가지 파버카스텔 색연필 색상 집합에서 가장 가까운 색상으로 매핑

In [ ]:
import numpy as np

# 12가지 파버카스텔 색연필 색상 집합 (RGB 값 예시)
faber_castell_colors = {
    "white" : (255, 255, 255),
    "Black" : (0, 0, 0),
    "Brown" : (150, 75, 0),
    "Orange" : (225, 127, 0),
    "Red" : (255, 0, 0),
    "Yellow" : (255, 255, 0),
    "Light Green" : (0, 255, 0),
    "Green" : (0, 128, 0),
    "Light Blue": (0, 255, 255),
    "Blue": (0, 0, 255),
    "Purple": (128, 0, 128),
    "Pink": (255, 192, 203),
}

# 입력 색상 (예: 사용자 입력값)
input_color = (120, 100, 200)  # 예를 들어 보라색 계열


def find_nearest_color(input_rgb, color_set):
  min_dist = float("inf")
  nearest_name = None
  for name, rgb in color_set.items():
    # 유클리드 거리 계산
    dist = np.sqrt(sum((a - b) ** 2 for a, b in zip(input_rgb, rgb)))
    if dist < min_dist:
      min_dist = dist
      nearest_name = name
  return nearest_name, color_set[nearest_name]


nearest_name, nearest_rgb = find_nearest_color(
    input_color, faber_castell_colors
)

print(f"입력 색상: {input_color}")
print(f"가장 가까운 파버카스텔 색상: {nearest_name}, RGB: {nearest_rgb}")

입력 색상: (120, 100, 200)
가장 가까운 파버카스텔 색상: Purple, RGB: (128, 0, 128)


In [ ]:
# Colab 환경: 필요한 라이브러리 설치
!pip install pillow numpy matplotlib

# 라이브러리 import
from PIL import Image
from google.colab import files
import matplotlib.pyplot as plt
import numpy as np

# 파버카스텔 색연필 12색 (RGB 근사값)
faber_castell_colors = {
    "White": (255, 255, 255),
    "Black": (0, 0, 0),
    "Brown": (150, 75, 0),
    "Orange": (255, 127, 0),
    "Red": (255, 0, 0),
    "Yellow": (255, 255, 0),
    "Light Green": (0, 255, 0),
    "Green": (0, 128, 0),
    "Light Blue": (0, 255, 255),
    "Blue": (0, 0, 255),
    "Purple": (128, 0, 128),
    "Pink": (255, 192, 203),
}


# 가장 가까운 색상 찾기 함수
def find_nearest_color(pixel, color_set):
  min_dist = float("inf")
  nearest_rgb = (0, 0, 0)
  for rgb in color_set.values():
    dist = np.linalg.norm(np.array(pixel) - np.array(rgb))
    if dist < min_dist:
      min_dist = dist
      nearest_rgb = rgb
  return nearest_rgb


# 파일 업로드
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# 이미지 열기
image = Image.open(image_path).convert("RGB")
image_np = np.array(image)

# 출력용 배열 초기화
output_np = np.zeros_like(image_np)

# 픽셀 단위로 색상 변환
for i in range(image_np.shape[0]):
  for j in range(image_np.shape[1]):
    output_np[i, j] = find_nearest_color(
        image_np[i, j], faber_castell_colors
    )

# 변환 결과 이미지
output_image = Image.fromarray(output_np)

# 원본과 변환 이미지를 함께 시각화
fig, axs = plt.subplots(1, 2, figsize=(12, 6))
axs[0].imshow(image)
axs[0].set_title("Original Image")
axs[0].axis("off")

axs[1].imshow(output_image)
axs[1].set_title("Mapped to Faber-Castell 12 Colors")
axs[1].axis("off")

plt.show()

KeyboardInterrupt: 

# 관계 굵은 텍스트 : 이항 관련 예제

In [5]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A = {1,2,3}
B = {2,3,4}
# A에서 B로 가는 이항 관계 R
R = {(1,2),(2,3),(3,2),(3,4)}

print("관계R : ",R)

관계R :  {(2, 3), (3, 2), (1, 2), (3, 4)}


# 관계 행렬 표현

In [10]:
A_list = sorted(A)
B_list = sorted(B)

# np.zeros의 첫 번째 인자인 shape은 (row, col) 형태의 튜플로 전달해야 합니다.
relation_matrix = np.zeros((len(A_list), len(B_list)), dtype=int)

for i, a in enumerate(A_list):
    for j, b in enumerate(B_list):
        if (a, b) in R:
            relation_matrix[i, j] = 1

print("관계 행렬 (rows: A, columns : B):")
print(relation_matrix)

관계 행렬 (rows: A, columns : B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


# 합성 관계 예제

In [12]:
# R : A -> B
# S : B -> C
C = {'x','y'}
# {4, 'x'} 대신 튜플 (4, 'x')를 사용하여 unhashable set 오류를 해결합니다.
S = {(2, 'x'), (3, 'y'), (4, 'x')}

# 합성 관계 R * S
composed_relation = set()

for (a,b1) in R:
  for (b2, c) in S :
    if b1 == b2:
      composed_relation.add((a,c))

print("\n합성 관계 R * S:", composed_relation)


합성 관계 R * S: {(1, 'x'), (2, 'y'), (3, 'x')}
